//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaktuz_Company.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Awarded_Cactus
    {
        public int id_awarded { get; set; }
        public Nullable<int> id_cactus { get; set; }
        public Nullable<int> id_exhibition { get; set; }
    
        public virtual Cactus Cactus { get; set; }
        public virtual Exhibition Exhibition { get; set; }
    }
}
