//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaktuz_Company.bd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kaktuscompanyEntities1 : DbContext
    {
        public kaktuscompanyEntities1()
            : base("name=kaktuscompanyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Awarded_Cactus> Awarded_Cactus { get; set; }
        public virtual DbSet<Cactus> Cactus { get; set; }
        public virtual DbSet<Exhibition> Exhibition { get; set; }
        public virtual DbSet<participant> participant { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
